-- ─────────────────────────────────────────────────────────────
-- TechPulse — Seed : référentiel canonique des technologies
-- 180+ technos avec aliases JSON pour matching NLP
-- ─────────────────────────────────────────────────────────────

USE techpulse;

INSERT IGNORE INTO technologies (canonical_name, display_name, category, aliases) VALUES
-- ─── Langages de programmation ───
('python',          'Python',         'language',   JSON_ARRAY('py', 'python3')),
('javascript',      'JavaScript',     'language',   JSON_ARRAY('js', 'ecmascript', 'es6', 'es2015')),
('typescript',      'TypeScript',     'language',   JSON_ARRAY('ts')),
('java',            'Java',           'language',   JSON_ARRAY('jdk', 'jre')),
('csharp',          'C#',             'language',   JSON_ARRAY('c#', 'csharp', 'c sharp')),
('cpp',             'C++',            'language',   JSON_ARRAY('c++', 'cpp')),
('c',               'C',              'language',   JSON_ARRAY('langage c')),
('go',              'Go',             'language',   JSON_ARRAY('golang')),
('rust',            'Rust',           'language',   JSON_ARRAY()),
('php',             'PHP',            'language',   JSON_ARRAY()),
('ruby',            'Ruby',           'language',   JSON_ARRAY('rb')),
('kotlin',          'Kotlin',         'language',   JSON_ARRAY()),
('swift',           'Swift',          'language',   JSON_ARRAY()),
('scala',           'Scala',          'language',   JSON_ARRAY()),
('r',               'R',              'language',   JSON_ARRAY('r language', 'langage r')),
('matlab',          'MATLAB',         'language',   JSON_ARRAY()),
('dart',            'Dart',           'language',   JSON_ARRAY()),
('elixir',          'Elixir',         'language',   JSON_ARRAY()),
('clojure',         'Clojure',        'language',   JSON_ARRAY()),
('haskell',         'Haskell',        'language',   JSON_ARRAY()),
('lua',             'Lua',            'language',   JSON_ARRAY()),
('perl',            'Perl',           'language',   JSON_ARRAY()),
('bash',            'Bash',           'language',   JSON_ARRAY('shell', 'shell script')),
('powershell',      'PowerShell',     'language',   JSON_ARRAY('ps1')),
('sql',             'SQL',            'language',   JSON_ARRAY()),
('groovy',          'Groovy',         'language',   JSON_ARRAY()),
('julia',           'Julia',          'language',   JSON_ARRAY()),
('objective-c',     'Objective-C',    'language',   JSON_ARRAY('objc')),
('vbnet',           'VB.NET',         'language',   JSON_ARRAY('vb.net', 'visual basic .net')),
('fsharp',          'F#',             'language',   JSON_ARRAY('f#', 'fsharp')),

-- ─── Frameworks web / mobile ───
('react',           'React',          'framework',  JSON_ARRAY('reactjs', 'react.js')),
('vue',             'Vue.js',         'framework',  JSON_ARRAY('vuejs', 'vue.js', 'vue 3')),
('angular',         'Angular',        'framework',  JSON_ARRAY('angularjs', 'angular 2+')),
('svelte',          'Svelte',         'framework',  JSON_ARRAY('sveltejs')),
('sveltekit',       'SvelteKit',      'framework',  JSON_ARRAY()),
('nextjs',          'Next.js',        'framework',  JSON_ARRAY('next', 'next.js')),
('nuxtjs',          'Nuxt.js',        'framework',  JSON_ARRAY('nuxt', 'nuxt.js')),
('remix',           'Remix',          'framework',  JSON_ARRAY()),
('astro',           'Astro',          'framework',  JSON_ARRAY()),
('express',         'Express',        'framework',  JSON_ARRAY('expressjs', 'express.js')),
('fastify',         'Fastify',        'framework',  JSON_ARRAY()),
('nestjs',          'NestJS',         'framework',  JSON_ARRAY('nest.js', 'nest')),
('fastapi',         'FastAPI',        'framework',  JSON_ARRAY()),
('flask',           'Flask',          'framework',  JSON_ARRAY()),
('django',          'Django',         'framework',  JSON_ARRAY()),
('rails',           'Ruby on Rails',  'framework',  JSON_ARRAY('ror', 'ruby on rails')),
('laravel',         'Laravel',        'framework',  JSON_ARRAY()),
('symfony',         'Symfony',        'framework',  JSON_ARRAY()),
('spring-boot',     'Spring Boot',    'framework',  JSON_ARRAY('spring', 'springboot')),
('aspnet',          'ASP.NET Core',   'framework',  JSON_ARRAY('asp.net', 'asp.net core', '.net')),
('dotnet',          '.NET',           'framework',  JSON_ARRAY('.net', 'dotnet', 'dotnet core')),
('gin',             'Gin',            'framework',  JSON_ARRAY('gin-gonic')),
('echo',            'Echo',           'framework',  JSON_ARRAY()),
('phoenix',         'Phoenix',        'framework',  JSON_ARRAY()),
('tailwind',        'Tailwind CSS',   'framework',  JSON_ARRAY('tailwindcss', 'tailwind css')),
('bootstrap',       'Bootstrap',      'framework',  JSON_ARRAY()),
('material-ui',     'Material UI',    'framework',  JSON_ARRAY('mui', 'material-ui')),
('chakra-ui',       'Chakra UI',      'framework',  JSON_ARRAY('chakra', 'chakra-ui')),
('solidjs',         'SolidJS',        'framework',  JSON_ARRAY('solid', 'solid.js')),
('qwik',            'Qwik',           'framework',  JSON_ARRAY()),
('alpinejs',        'Alpine.js',      'framework',  JSON_ARRAY('alpine', 'alpinejs')),
('htmx',            'HTMX',           'framework',  JSON_ARRAY('htmx')),
('react-native',    'React Native',   'framework',  JSON_ARRAY('rn', 'react native')),
('flutter',         'Flutter',        'framework',  JSON_ARRAY()),
('ionic',           'Ionic',          'framework',  JSON_ARRAY()),
('electron',        'Electron',       'framework',  JSON_ARRAY()),
('jquery',          'jQuery',         'framework',  JSON_ARRAY()),
('quasar',          'Quasar',         'framework',  JSON_ARRAY()),

-- ─── Bases de données ───
('mysql',           'MySQL',          'database',   JSON_ARRAY('mariadb')),
('postgresql',      'PostgreSQL',     'database',   JSON_ARRAY('postgres', 'psql')),
('mariadb',         'MariaDB',        'database',   JSON_ARRAY()),
('sqlite',          'SQLite',         'database',   JSON_ARRAY()),
('oracle-db',       'Oracle',         'database',   JSON_ARRAY('oracle db', 'oracle database')),
('sqlserver',       'SQL Server',     'database',   JSON_ARRAY('mssql', 'ms sql server', 't-sql')),
('mongodb',         'MongoDB',        'database',   JSON_ARRAY('mongo')),
('redis',           'Redis',          'database',   JSON_ARRAY()),
('cassandra',       'Cassandra',      'database',   JSON_ARRAY('apache cassandra')),
('dynamodb',        'DynamoDB',       'database',   JSON_ARRAY('dynamo')),
('neo4j',           'Neo4j',          'database',   JSON_ARRAY()),
('elasticsearch',   'Elasticsearch',  'database',   JSON_ARRAY('elastic', 'es')),
('opensearch',      'OpenSearch',     'database',   JSON_ARRAY()),
('firebase',        'Firebase',       'database',   JSON_ARRAY('firestore')),
('supabase',        'Supabase',       'database',   JSON_ARRAY()),
('snowflake',       'Snowflake',      'database',   JSON_ARRAY()),
('bigquery',        'BigQuery',       'database',   JSON_ARRAY('big query', 'gcp bigquery')),
('redshift',        'Redshift',       'database',   JSON_ARRAY('aws redshift')),
('clickhouse',      'ClickHouse',     'database',   JSON_ARRAY()),
('influxdb',        'InfluxDB',       'database',   JSON_ARRAY()),

-- ─── Cloud & infrastructure ───
('aws',             'AWS',            'cloud',      JSON_ARRAY('amazon web services', 'amazon aws')),
('azure',           'Azure',          'cloud',      JSON_ARRAY('microsoft azure', 'ms azure')),
('gcp',             'Google Cloud',   'cloud',      JSON_ARRAY('google cloud platform', 'gcp')),
('heroku',          'Heroku',         'cloud',      JSON_ARRAY()),
('vercel',          'Vercel',         'cloud',      JSON_ARRAY()),
('netlify',         'Netlify',        'cloud',      JSON_ARRAY()),
('railway',         'Railway',        'cloud',      JSON_ARRAY()),
('flyio',           'Fly.io',         'cloud',      JSON_ARRAY('fly.io', 'fly io')),
('digitalocean',    'DigitalOcean',   'cloud',      JSON_ARRAY('digital ocean')),
('ovh',             'OVH',            'cloud',      JSON_ARRAY('ovhcloud')),
('scaleway',        'Scaleway',       'cloud',      JSON_ARRAY()),
('cloudflare',      'Cloudflare',     'cloud',      JSON_ARRAY()),
('aws-lambda',      'AWS Lambda',     'cloud',      JSON_ARRAY('lambda')),
('aws-s3',          'AWS S3',         'cloud',      JSON_ARRAY('s3', 'amazon s3')),
('aws-ec2',         'AWS EC2',        'cloud',      JSON_ARRAY('ec2')),
('aws-rds',         'AWS RDS',        'cloud',      JSON_ARRAY('rds')),
('cloudrun',        'Cloud Run',      'cloud',      JSON_ARRAY('gcp cloud run')),

-- ─── Outils (build, CI/CD, monitoring, queues) ───
('docker',          'Docker',         'tool',       JSON_ARRAY('docker-compose', 'docker compose')),
('kubernetes',      'Kubernetes',     'tool',       JSON_ARRAY('k8s', 'kube')),
('terraform',       'Terraform',      'tool',       JSON_ARRAY('hashicorp terraform')),
('ansible',         'Ansible',        'tool',       JSON_ARRAY()),
('jenkins',         'Jenkins',        'tool',       JSON_ARRAY()),
('gitlab-ci',       'GitLab CI',      'tool',       JSON_ARRAY('gitlab ci', 'gitlab ci/cd')),
('github-actions',  'GitHub Actions', 'tool',       JSON_ARRAY('gh actions', 'github ci')),
('circleci',        'CircleCI',       'tool',       JSON_ARRAY('circle ci')),
('git',             'Git',            'tool',       JSON_ARRAY()),
('webpack',         'Webpack',        'tool',       JSON_ARRAY()),
('vite',            'Vite',           'tool',       JSON_ARRAY()),
('rollup',          'Rollup',         'tool',       JSON_ARRAY()),
('esbuild',         'ESBuild',        'tool',       JSON_ARRAY()),
('babel',           'Babel',          'tool',       JSON_ARRAY()),
('npm',             'npm',            'tool',       JSON_ARRAY()),
('yarn',            'Yarn',           'tool',       JSON_ARRAY()),
('pnpm',            'pnpm',           'tool',       JSON_ARRAY()),
('pip',             'pip',            'tool',       JSON_ARRAY()),
('poetry',          'Poetry',         'tool',       JSON_ARRAY()),
('maven',           'Maven',          'tool',       JSON_ARRAY('apache maven')),
('gradle',          'Gradle',         'tool',       JSON_ARRAY()),
('nginx',           'Nginx',          'tool',       JSON_ARRAY()),
('apache',          'Apache',         'tool',       JSON_ARRAY('apache httpd', 'apache2')),
('prometheus',      'Prometheus',     'tool',       JSON_ARRAY()),
('grafana',         'Grafana',        'tool',       JSON_ARRAY()),
('datadog',         'Datadog',        'tool',       JSON_ARRAY()),
('sentry',          'Sentry',         'tool',       JSON_ARRAY()),
('kafka',           'Kafka',          'tool',       JSON_ARRAY('apache kafka')),
('rabbitmq',        'RabbitMQ',       'tool',       JSON_ARRAY()),
('celery',          'Celery',         'tool',       JSON_ARRAY()),
('airflow',         'Apache Airflow', 'tool',       JSON_ARRAY('airflow')),
('dbt',             'dbt',            'tool',       JSON_ARRAY('data build tool')),
('spark',           'Apache Spark',   'tool',       JSON_ARRAY('pyspark', 'spark')),
('hadoop',          'Hadoop',         'tool',       JSON_ARRAY('apache hadoop')),

-- ─── Bibliothèques ───
('numpy',           'NumPy',          'library',    JSON_ARRAY()),
('pandas',          'Pandas',         'library',    JSON_ARRAY()),
('polars',          'Polars',         'library',    JSON_ARRAY()),
('scipy',           'SciPy',          'library',    JSON_ARRAY()),
('scikit-learn',    'scikit-learn',   'library',    JSON_ARRAY('sklearn', 'scikit learn')),
('tensorflow',      'TensorFlow',     'library',    JSON_ARRAY('tf')),
('pytorch',         'PyTorch',        'library',    JSON_ARRAY('torch')),
('keras',           'Keras',          'library',    JSON_ARRAY()),
('xgboost',         'XGBoost',        'library',    JSON_ARRAY('xgb')),
('lightgbm',        'LightGBM',       'library',    JSON_ARRAY('lgbm')),
('huggingface',     'Hugging Face',   'library',    JSON_ARRAY('transformers', 'hf')),
('langchain',       'LangChain',      'library',    JSON_ARRAY()),
('spacy',           'spaCy',          'library',    JSON_ARRAY()),
('nltk',            'NLTK',           'library',    JSON_ARRAY()),
('opencv',          'OpenCV',         'library',    JSON_ARRAY('cv2')),
('matplotlib',      'Matplotlib',     'library',    JSON_ARRAY()),
('seaborn',         'Seaborn',        'library',    JSON_ARRAY()),
('plotly',          'Plotly',         'library',    JSON_ARRAY()),
('chartjs',         'Chart.js',       'library',    JSON_ARRAY('chart.js')),
('d3js',            'D3.js',          'library',    JSON_ARRAY('d3', 'd3.js')),
('threejs',         'Three.js',       'library',    JSON_ARRAY('three.js')),
('leaflet',         'Leaflet',        'library',    JSON_ARRAY('leaflet.js')),
('socketio',        'Socket.IO',      'library',    JSON_ARRAY('socket.io')),
('graphql',         'GraphQL',        'library',    JSON_ARRAY()),
('apollo',          'Apollo',         'library',    JSON_ARRAY('apollo client', 'apollo server')),
('grpc',            'gRPC',           'library',    JSON_ARRAY()),
('axios',           'Axios',          'library',    JSON_ARRAY()),
('redux',           'Redux',          'library',    JSON_ARRAY()),
('zustand',         'Zustand',        'library',    JSON_ARRAY()),
('rxjs',            'RxJS',           'library',    JSON_ARRAY()),
('lodash',          'Lodash',         'library',    JSON_ARRAY()),
('jest',            'Jest',           'library',    JSON_ARRAY()),
('vitest',          'Vitest',         'library',    JSON_ARRAY()),
('cypress',         'Cypress',        'library',    JSON_ARRAY()),
('playwright',      'Playwright',     'library',    JSON_ARRAY()),
('selenium',        'Selenium',       'library',    JSON_ARRAY()),
('puppeteer',       'Puppeteer',      'library',    JSON_ARRAY()),
('pytest',          'pytest',         'library',    JSON_ARRAY()),
('junit',           'JUnit',          'library',    JSON_ARRAY()),
('phpunit',         'PHPUnit',        'library',    JSON_ARRAY()),
('sqlalchemy',      'SQLAlchemy',     'library',    JSON_ARRAY()),
('prisma',          'Prisma',         'library',    JSON_ARRAY()),
('hibernate',       'Hibernate',      'library',    JSON_ARRAY()),
('entity-framework','Entity Framework','library',   JSON_ARRAY('ef core', 'entity framework core')),
('pydantic',        'Pydantic',       'library',    JSON_ARRAY()),
('beautifulsoup',   'BeautifulSoup',  'library',    JSON_ARRAY('bs4', 'beautiful soup')),
('scrapy',          'Scrapy',         'library',    JSON_ARRAY()),
('requests',        'Requests',       'library',    JSON_ARRAY()),
('httpx',           'httpx',          'library',    JSON_ARRAY()),

-- ─── Méthodologies ───
('agile',           'Agile',          'methodology', JSON_ARRAY('agilité')),
('scrum',           'Scrum',          'methodology', JSON_ARRAY()),
('kanban',          'Kanban',         'methodology', JSON_ARRAY()),
('devops',          'DevOps',         'methodology', JSON_ARRAY()),
('ci-cd',           'CI/CD',          'methodology', JSON_ARRAY('ci/cd', 'cicd', 'intégration continue')),
('tdd',             'TDD',            'methodology', JSON_ARRAY('test driven development', 'test-driven development')),
('bdd',             'BDD',            'methodology', JSON_ARRAY('behavior driven development')),
('ddd',             'DDD',            'methodology', JSON_ARRAY('domain driven design', 'domain-driven design')),
('clean-architecture','Clean Architecture','methodology', JSON_ARRAY('clean archi')),
('microservices',   'Microservices',  'methodology', JSON_ARRAY('micro-services', 'microservice')),
('rest',            'REST',           'methodology', JSON_ARRAY('rest api', 'restful')),
('serverless',      'Serverless',     'methodology', JSON_ARRAY('sans serveur')),
('oauth',           'OAuth',          'methodology', JSON_ARRAY('oauth2', 'oauth 2')),
('jwt',             'JWT',            'methodology', JSON_ARRAY('json web token'));
